name: Deploy to VPS

on:
  push:
    branches:
      - main # This triggers the workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH for deployment
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: SSH into VPS and deploy frontend
      - name: Deploy frontend to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/biggergig/hosting/portfolio
            git pull
            cd /home/biggergig/hosting/portfolio/frontend 
            npm install  # To make sure dependencies are up to date
            npm run build
          EOF


      # Step 4: SSH into VPS and deploy backend
      - name: Deploy backend to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/biggergig/hosting/portfolio/backend
            git pull
            echo "whoamI returns" `whoami`"."
            sudo /bin/systemctl restart anshumandash  # Restart your systemctl service
          EOF